<?php include TPL_MAIN_HEADER ?>
<style>
.title{padding: 10px 15px;}
.backarea{border-top: 1px solid #e5e5e5;background: #eee;border-radius: 3px;}
.goback{margin: 5px 0 5px 90%;}
.showTreeData{display: none;}
#dataTreeView{width: 390px;margin:10px 10px;float: left;border-left:1px solid #ddd;border-right:1px solid #ddd;border-bottom: 1px solid #ddd;}
#change-treeview{margin: 0 15px;}
.serveType{margin-right: 20px;}
.form_datetime{width: 200px !important; display: inline-block;}
.err{ width: 290px;height: 40px; position: absolute;top: 40px;left: 164px; background: url(/img/tip.png) no-repeat; background-size: 100% 100%; padding: 10px 10px; color: #f00;z-index: 10;display: none;}
table th,td{text-align: center;}
.SingleDataInfo{display: none;}
.showAllData{position:relative;}
.heightChartChange{position:absolute;top: 20px;}
.pie{left:20px;}
.column{left:100px;}
.show-left-menu{color:#2fa4e7;position: fixed;top: 50%;left: 5px;cursor: pointer;display: none;}
.loading-alldata{position: absolute;left: 45%;top:200px;}
.table-area{padding: 10px 10px;position: relative;}
.table-area .loading-data-list{position: absolute;top: 200px;left: 50%;display: none;}
.modal-dialog{width: 80% !important;}
iframe{width: 100%;min-height: 700px; }
.search-area{min-width:400px;position: absolute;border:1px solid #eee;left: 750px;top: 50px;padding: 10px 10px;border-radius: 4px;display: none;}
.search-area .search-item {width: 200px;float: left;}
.search-area .search-item .form-control{width: 100px;display: inline;}
.dataTables_paginate{;height: 40px;margin: 10px 0;border-radius: 4px;text-align: center;}
.dataTables_paginate .paginate_button{width: 30px;height: 30px;line-height: 1;text-align: center;display: inline-block;border: 1px solid #ddd;cursor: pointer;}
.dataTables_paginate .paginate_button:hover{text-decoration:none;}
.dataTables_paginate .first{width: 60px;}
.dataTables_paginate .last{width: 60px;}
.dataTables_paginate .next{width: 60px;}
.dataTables_paginate .previous{width: 60px;}
.dataTables_paginate .disabled{width: 60px;color: #999;cursor: not-allowed;}
.dataTables_paginate .current{background: #f5f5f5;color: #999}
.buttons-excel,.buttons-csv,.buttons-pdf{
    background-color: #177bbb;
    color: #fff;
    border-color: #177bbb;
    display: inline-block;
    margin-bottom: 4px;
    font-weight: normal;
    text-align: center;
    vertical-align: middle;
    cursor: pointer;
    background-image: none;
    border: 1px solid transparent;
    white-space: nowrap;
    padding: 6px 12px;
    font-size: 14px;
    border-radius: 4px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
.show_data{display: block;position: relative;}
h3{position: absolute;left: 34%;top: 50px;}
.search-bar{margin: 20px 0;position: relative;}
table{width: 100% !important;}
.dataTables_wrapper{position: relative;overflow: visible;}
.dt-buttons{ text-align: right;padding: 10px; position: absolute;right:0px;top: -16px;}
.buttons-excel,.buttons-csv,.buttons-pdf{color: #fff !important;border-bottom: 0;margin-right: 10px;}
td{vertical-align:middle !important;}
.issue_type{width: 150px !important;margin-bottom: 10px;float: left; margin-right: 10px;}
.search_sub{margin-left: 306px;}
.loading-data-list{position: absolute;top: 200px;left: 50%;display: block;}
</style>
<div class="ch-container">
    <div class="row">
        <?php include TPL_LEFT_ISSUE_MENU ?>
        <div id="content" class="col-lg-10 col-sm-10">
            <!-- content starts -->
            <div>
                <ul class="breadcrumb">
                    <li><a href="/index">首页</a></li>
                    <li>IFOS事务跟踪</li>
                    <li>数据统计</li>
                    <li>域名统计</li>
                </ul>
            </div>
            <div class="row">
                <div class="box col-md-12">
                    <div class="box-inner">
                        <div class="box-header well" data-original-title="">
                            <h2><i class="glyphicon glyphicon-magnet"></i> 域名统计</h2>

                            <div class="box-icon">
                                <a href="#" class="btn btn-minimize btn-round btn-default"><i
                                        class="glyphicon glyphicon-chevron-up"></i></a>
                                <a href="#" class="btn btn-close btn-round btn-default"><i
                                        class="glyphicon glyphicon-remove"></i></a>
                            </div>
                        </div>
                        <div class="box-content">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="data_area">
                                        <div class="show_data">
                                            <div class="show_data">
                                            <div class="search-bar">
                                                <select name="" class="form-control issue_type">
                                                    <option value="">所有域名</option>
                                                    <option value="staffifengcom">staff.ifeng.com</option>
                                                    <option value="ifengidccom">ifengidc.com</option>
                                                    <option value="ifengimgcom">ifengimg.com</option>
                                                    <option value="ifengcom">ifeng.com</option>
                                                    <option value="othercom">其他</option>
                                                </select>
                                                <input type="text" class="form-control form_datetime" issueType="1" name="t_start_time" data-label="停用时间" readonly="" placeholder="开始时间" value="">
                                                <input type="text" class="form-control form_datetime" issueType="1" name="t_end_time" data-label="停用时间" readonly="" placeholder="结束时间">
                                                 <a class="btn btn-primary search_btn" href="#">
                                                    <i class="glyphicon glyphicon-search"></i> 搜索
                                                </a>
                                                <p class="err js_err">开始时间必须小于结束时间</p>
                                            </div>
                                            <!-- <h3 class="js_allCheckTime">审批平均时间</h3> -->
                                            <img class="loading-data-list" src="/img/ajax-loaders/ajax-loader-6.gif" title="img/ajax-loaders/ajax-loader-6.gif">
                                            <div class="data-list">

                                                <table class="table table-striped table-bordered js_DataInfo">
                                                </table>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/span-->
                </div>
                <!--/row-->
            </div>
        </div>
    </div>
</div>
    
<?php include TPL_MAIN_FOOTER ?>
<!-- jQuery -->
<script src="/js/jquery/jquery.min.js"></script>
<script src="/js/bootstrap/bootstrap.min.js"></script>
<script src="/js/bootstrap/bootstrap-treeview.min.js"></script>
<script src="/js/bootstrap/bootstrap-datetimepicker.min.js"></script>
<script src="/js/bootstrap/locales/bootstrap-datetimepicker.zh-CN.js"></script>

<script type="text/javascript"  src='/js/jquery/jquery.dataTables1.10.16.min.js'></script>    

<script src='/js/dataTables.buttons.min.js'></script>    
<script src='/js/jszip.min.js'></script>    
<script src='/js/buttons.html5.min.js'></script> 

<script src="/js/jquery.tools.js"></script>
<script src="/js/ifos.js"></script>
<script type="text/javascript">
   
    $(document).ready(function () {

        var list = {
            init: function(){
                var that = this;
                $('#IssueData').addClass('active').find('ul').slideToggle();
                $('#IssueData-domain').css({
                    "background-color": "#eeeeee"
                });
                $(".form_datetime").datetimepicker({
                    'language': 'zh-CN',
                    'minView': "month",
                    'format': "yyyy-mm-dd",
                    'autoclose':true,
                    'showMeridian':true,
                    'todayBtn':true
                });
                that.getData()

                $(document).on('change','.issue_type', function() {
                    $(".search_btn").trigger("click");
                })
                $(document).on('change','.form_datetime', function() {
                    $(".search_btn").trigger("click");
                })
                
                $(document).on('click','.search_btn', function() {
                    var start = $("input[name='t_start_time']").val()
                    var end = $("input[name='t_end_time']").val()

                    if(new Date(start.replace(/-/g, "/")).getTime() >new Date(end.replace(/-/g, "/")).getTime()){// 开始时间大于结束时间

                        $(".search-bar").find(".js_err").html('<label id="t_port-error" class="error" for="t_port">开始时间必须小于结束时间.</label>')
                        $(".search-bar").find(".js_err").show();
                        return false;
                    }else{
                        $(".search-bar").find(".js_err").hide();
                        that.getData()
                    }
                })
            },
            getData: function() {
                $(".data-list").empty();
                $(".loading-data-list").show();
                var that = this
                $.ifosAjax({
                    type: "get",
                    dataType: "json",
                    url: "/api/Issue_data/getDomainIssue?start="+$(".show_data").eq(0).find("input[name='t_start_time']").val()+"&end="+$(".show_data").eq(0).find("input[name='t_end_time']").val()+'&type='+$(".issue_type").val(),
                    error: function(err) {
                        console.log(err);
                    },
                    success: function(result) {
                        
                        $(".data-list").append('<table class="table table-striped table-bordered js_DataInfo"></table>')
                        that.renderData(result.aaData)
                    }
                });
            },
            renderData: function(dataList) {
                $('.js_DataInfo').DataTable( {
                    'dom': 'liBtrp',
                    "sPaginationType": "full_numbers",
                    'buttons': [{ 
                        "extend": 'excelHtml5', 
                        'title': '域名统计',//导出文件名  
                        'text': '导出Excel',//定义导出excel按钮的文字  
                        customize: function( xlsx ) { 
                            var sheet = xlsx.xl.worksheets['sheet1.xml']; 
                            // $('row c[r^="C"]', sheet).attr( 's', '2' ); 
                        } 
                    }],
                    'lengthMenu': [
                        [ 10, 25, 50, 100, 1000000 ],
                        [ '10', '25', '50', '100','所有' ]
                    ],
                    // 'buttons': [
                    //     'pageLength'
                    // ]
                    // "bServerSide": true,
                    "bDestroy":true,
                    data: dataList,
                    // "searching": true
                    // "sAjaxSource": "/api/Issue_data/getDomainIssue?start="+$(".show_data").eq(0).find("input[name='t_start_time']").val()+"&end="+$(".show_data").eq(0).find("input[name='t_end_time']").val()+'&type='+$(".issue_type").val(),
                    "aoColumns": [
                        {
                            "sTitle": "提案号",
                            "sWidth": "4%",
                            "mDataProp": "id"
                        }, {
                            "sTitle": "域名",
                            "sWidth": "35%",
                            "mDataProp": "domain"
                        }, {
                            "sTitle": "提案",
                            "sWidth": "13%",
                            "mDataProp": "name"
                        }, {
                            "sTitle": "提案标题",
                            "sWidth": "13%",
                            "mDataProp": "title"
                        }, {
                            "sTitle": "申请人",
                            "sWidth": "8%",
                            "mDataProp": "applicant"
                        }, {
                            "sTitle": "部门",
                            "sWidth": "22%",
                            "mDataProp": "department"
                        }, {
                            "sTitle": "时间",
                            "sWidth": "20%",
                            "sClass": "center",
                            "mDataProp": "time"
                        }
                    ],
                    "oLanguage": {
                        "sProcessing": "处理中...",
                        "sLengthMenu": "显示 _MENU_ 项结果",
                        "sZeroRecords": "没有匹配结果",
                        "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                        "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
                        "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
                        "sInfoPostFix": "",
                        "sSearch": "搜索:",
                        "sUrl": "",
                        "sEmptyTable": "表中数据为空",
                        "sLoadingRecords": "载入中...",
                        "sInfoThousands": ",",
                        "oPaginate": {
                            "sFirst": "首页",
                            "sPrevious": "上页",
                            "sNext": "下页",
                            "sLast": "末页"
                        },
                        "oAria": {
                            "sSortAscending": ": 以升序排列此列",
                            "sSortDescending": ": 以降序排列此列"
                        }
                    },
                    'ordering':true,
                    "aaSorting": [0, "desc"],
                    "aoColumnDefs": [
                    {
                        "aTargets": [0],
                        "mRender": function (data, type, item) {
                            var html = '<a class="btn btn-primary btn-sm" href="/issue/server/detail?id=' + data + '&no-cache=' + Math.random()+'">';
                            html += data;
                            html += '</a>';
                            return html
                        }
                    }
                    ]
                } );
                $(".loading-data-list").hide()

                if($(window).height()>$("body").height()){
                    $('footer').css({'position':'absolute','padding':'0 20px'})
                }else{
                    $('footer').css({'position':'static','padding':'0 0px'})
                }

            }
        }
        list.init();
      
    });
</script>
