<?php include TPL_LOGIN_HEADER ?>
<body>
    <style>
        body{background: url(/img/login_bg1.jpg) no-repeat center center #bec5ca;}
        .login-header .logo{width: 50px;height: 50px;margin-right: 10px;vertical-align:-14px;}
        form{margin-top: 20px;position: relative;}
        form .input-prepend{margin-top: 10px;}
        form .login_action{margin-top: -20px;}
        #alertInfo{width: 0px;height: 38px;position: absolute;bottom: -10px;right: -123px;display: none;overflow: hidden;line-height: 38px;padding:  0 0;}
    </style>
<div class="ch-container">
    <div class="row">
        <div class="col-md-12 center login-header">
            <h2><img class="logo" src="/img/logo10.png" alt="">您已登出 PMS 系统，谢谢</h2>
        </div>
    </div>
    <div class="row" style="visibility:hidden;">
        <div class="well col-md-5 center login-box">
            <form class="form-horizontal">
                <fieldset>
                    <div class="input-group input-group-lg">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user red"></i></span>
                        <input name="usr" type="text" class="form-control" required="required" placeholder="请输入您的用户名">
                    </div>
                    <div class="clearfix"></div>
                    <br>
                    <div class="input-group input-group-lg">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock red"></i></span>
                        <input name="pwd" type="password" class="form-control" required="required" placeholder="请输入您的密码">
                    </div>
                    <div class="clearfix"></div>

                    <div class="input-prepend">
<!--                        <label class="remember" for="remember"><input type="checkbox" id="remember"> 5天内自动登录</label>-->
                        <label class="remember" for="remember"></label>
                    </div>
                    <div class="clearfix"></div>

                    <p class="login_action center col-md-5">
                        <button id="loginButton" type="submit" class="btn btn-primary">登录</button>
                    </p>
                </fieldset>
                <div class="alert alert-info" id="alertInfo">
                </div>
            </form>
        </div>
        <!--/span-->
    </div>
    <!--/row-->
</div>
<!--/fluid-row-->

<!-- jQuery -->
<script src="js/jquery/jquery.min.js"></script>
<script src="/js/jquery.tools.js"></script>
</body>
</html>