<html lang="zh-CN"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>全国 - 卖车 - 锐车</title>
    <meta content="" name="keywords">
    <meta content="" name="description">
    <link rel="stylesheet" href="/css/layui.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.3.2.js"></script>
    <script type="text/javascript" src="/js/jquery.form.js"></script>
    <script src="/js/layui.js"></script>
    <script src="/js/search.js"></script>
    <script language="JavaScript">
        layui.config({
            dir: '/static/layui/'
            ,version: false
            ,debug: false
            ,base: '/static/layui/lay/modules/'
        });

        layui.use('layer', function(){
            var layer = layui.layer;
        });

        $(function() {

            //alert(document.getElementsByTagName('meta')['ArticleTitle'].getAttribute('content'));
            //选择省份城市
            $("#province").selectOption('province');
            //选择品牌车型
            $("#brand").selectOption('brand');

            //选择车系
            $(document).on("click",".selectbrand",function(){
                var brandid = $(this).attr("data-index");
                $.get("/index.php?m=ajax&ajax=1&subbrand=1&abrandid="+brandid, {
                }, function (data, textStatus){
                    $('#selectsubbox').show().html(data);
                });
            });

            //选择车款
            $(document).on("click",".selectseries",function(){
                var subbrandid = $(this).attr("data-index");
                $.get("/index.php?m=ajax&ajax=1&subsubbrand=1&asubbrandid="+subbrandid, {
                }, function (data, textStatus){
                    $('#selectsubsubbox').show().html(data);
                });
            });

            $(document).on("click",".optionlist li",function(){
                var idname = $(this).attr('option-name');
                var idvalue = $(this).attr('data-index');
                if(idname=="province"){
                    if(idvalue==0){
                        $("#selectbox").hide();
                        $("#province").children("input[name="+idname+"]").val(idvalue);
                        $("#province").children("span").text($(this).text());
                    }
                    else{
                        $.get("/index.php?m=ajax&ajax=1&city=1&provinceid="+idvalue, {
                        }, function (data, textStatus){
                            $('#selectsubbox').show().html(data);
                        });
                    }
                }
                else{
                    $(window).scrollTop(pagetop);
                    $('html').css({"overflow":"auto"});
                    $('body').css({"overflow":"auto"});
                    if(idname=="city"){
                        $("#selectbox").hide();
                        $("#selectsubbox").hide();
                        $("#province").children("input[name=cid]").val(idvalue);
                        $("#province").children("span").text($(this).text());
                    }
                    else if(idname=="styles"){
                        $("#selectbox").hide();
                        $("#selectsubbox").hide();
                        $("#selectsubsubbox").hide();
                        $("#brand").children("input[name=subsubbrand]").val(idvalue);
                        $("#brand").children("span").text($(this).text());
                    }
                    else{
                        $("#selectbox").hide();
                        $("#"+idname+"").children("input[name="+idname+"]").val(idvalue);
                        $("#"+idname+"").children("span").text($(this).text());
                    }
                }
            });

            $(document).on("click","#reback",function(){
                $("#selectbox").hide();
                $('html').css({"overflow":"auto"});
                $('body').css({"overflow":"auto"});
            });

            $(document).on("click","#reback_subbrand",function(){
                $("#selectsubbox").hide();
            });
            $(document).on("click","#reback_subsubbrand",function(){
                $("#selectsubsubbox").hide();
            });
            $(document).on("click","#reback_city",function(){
                $("#selectsubbox").hide();
            });

            //表单提交
            var ajax_option={
                success:function(data){
                    var result = $.parseJSON(data);
                    if(result.code==1){
                        layer.msg(result.msg, {time: 1000, icon: 1});
                        setTimeout(function(){//两秒后跳转
                            location.href = result.url;
                        },1000);
                    }
                    else{
                        layer.msg(result.msg, {time: 1000, icon: 2});
                    }
                }
            };

            $("#ajaxForm").submit(function () {
                $(this).ajaxSubmit(ajax_option);
                return false;
            });

        });
    </script>
    <link id="layuicss-layer" rel="stylesheet" href="/static/layui/css/modules/layer/default/layer.css?v=3.1.1" media="all"></head>
<body>
<div id="mainbox">
    <!--内容-->
    <header class="mo-header">
        <div class="mo-header-left">
            <a href="/">
                首页
            </a>
            <i class="layui-icon"></i>
            <a href="#">
                快速卖车
            </a>
        </div>
    </header>
    <form method="post" action="/sellcar/" id="ajaxForm">
        <div class="addformlist">
            <ul>
                <li data="province" id="province"><span class="value">请选择城市</span>城市<i class="layui-icon"></i><input type="hidden" name="cid" value=""></li>
                <li data="brand" id="brand"><span class="value">请选择品牌</span>品牌<i class="layui-icon"></i><input type="hidden" name="subsubbrand" value=""></li>
                <li><span class="value"><input type="text" name="p_tel" value="" size="16" placeholder="请输入手机号"></span>手机号</li>
            </ul>
        </div>
        <div class="btn-box">
            <input type="submit" value="提交" class="layui-btn layui-btn-fluid layui-btn-danger"><input type="hidden" name="a" value="sell">
        </div>
    </form>
</div>
<div id="selectbox">
</div>
<div id="selectsubbox">
</div>
<div id="selectsubsubbox">
</div>

<div class="toolbar">
    <ul>
        <li><a href="/"><i class="a01"></i>首页</a></li>
        <li><a href="/buycar/buycar"><i class="a02"></i>买车</a></li>
        <li><a href="/sellcar/sellcar" class="selected"><i class="a03"></i>卖车</a></li>
        <li><a href="/center/center"><i class="a04"></i>我的</a></li>
    </ul>
</div>
<style>
    body{padding-bottom:70px;}
</style>
</body></html>