
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!-- <script src="http://vjs.zencdn.net/5.19/video.min.js"></script> -->
</head>

<body>
<!-- <div>
  <video controls="true" preload="auto" data-setup="{}">
    <source type="rtmp/flv" src="rtmp://10.80.34.151/live/N_IFENG_BAK_FHZX" />
  </video>
</div> -->
<div>
    <object id="forfun" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="400" height="300"
            codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0">
        <param name="movie" value="/seufld/seufld/flash/focus2.swf">
        <param name="quality" value="high">
        <param name="bgcolor" value="#F0F0F0">
        <param name="menu" value="false">
        <param name="wmode" value="opaque">
        <param name="FlashVars" value="">
        <param name="allowScriptAccess" value="sameDomain">
        <embed id="forfunex" src="/img/FlashDevelopWorkSpace.swf" width="400" height="300" align="middle" quality="high" bgcolor="#f0fff8"
               menu="false"
               play="true"
               loop="false"
               FlashVars=""
               allowScriptAccess="sameDomain"
               type="application/x-shockwave-flash"
               pluginspage="http://www.adobe.com/go/getflashplayer">
        </embed>
    </object>
</div>
<!-- <div>
  <p>
    <embed src="./flash6893.swf" type="application/x-shockwave-flash" width="550" height="400"
      quality="high" /><span style="line-height:1.5;"></span>
  </p>
</div> -->
<!-- <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
  codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="550"
  height="400" id="Untitled-1" align="middle">
  <param name="allowScriptAccess" value="sameDomain" />
  <param name="movie" value="./flash6893.swf" />
  <param name="quality" value="high" />
  <param name="bgcolor" value="#ffffff" />
  <embed src="./flash6893.swf" quality="high" bgcolor="#ffffff" width="550" height="400" name="mymovie" align="middle"
    allowScriptAccess="sameDomain" type="application/x-shockwave-flash"
    pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object> -->
<!-- <div>
  <object data="./flash6893.swf" type="application/x-shockwave-flash" width="1002" height="335">
    <param name="movie" value="./flash6893.swf" />
    <param name="wmode" value="transparent" />
  </object>
</div> -->
</body>

</html>