<html lang="zh-CN"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>身份认证</title>
    <meta content="" name="keywords">
    <meta content="" name="description">
    <link rel="stylesheet" href="/css/layui.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery.form.js"></script>
    <script src="/js/layui.js"></script>
</head>
<body>
<header class="mo-header">
    <div class="mo-header-left">
        <a href="/">
            首页
        </a>
        <i class="layui-icon"></i>
        <a href="/center/center">
            会员中心
        </a>
        <i class="layui-icon"></i>
        <a href="#">
            身份认证
        </a>
    </div>
</header>
<div class="main">
    <div class="btn-box">
        <a href="user.php?m=userinfo&amp;a=certify&amp;isdealer=1" class="layui-btn layui-btn-primary layui-btn-fluid">我是个人</a>
    </div>
    <div class="btn-box">
        <a href="user.php?m=userinfo&amp;a=certify&amp;isdealer=2" class="layui-btn layui-btn-primary layui-btn-fluid">我是企业</a>
    </div>
</div>



</body></html>