<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
    <title>二手车-首页</title>
    <link rel="stylesheet" type="text/css" href="/css/amazeui.css">
    <link rel="stylesheet" type="text/css" href="/css/common.css">
    <link rel="stylesheet" type="text/css" href="/css/header.css">
    <link rel="stylesheet" type="text/css" href="/font/iconfont.css">
</head>

<body style="padding-bottom:3rem;">
<header class="bgc">
    <div class="search_box">
        <div class="logo_box"><a href="index-old1.phtml" class="logo">logo</a></div>
        <input class="search_text" placeholder=""><button class="search_btn"><i class="icon iconfont icon-search fc8"></i></button>
        <a href="user_index.html" class="uc_icon"><i class="icon iconfont icon-yonghu1 fcf"></i></a>
    </div>
</header>
<div class="am-slider am-slider-default clearfix" data-am-flexslider="{playAfterPaused: 8000, directionNav: false}" id="slider">
    <ul class="am-slides">
        <li><img src="images/car1.jpg"/></li>
        <li><img src="images/car1.jpg"/></li>
    </ul>
</div>
<div class="sort_box pt1 pb1">
    <ul class="clearfix mb_15">
        <li class="mb15"><a href="list.html" class="fcf9">车主急售</a></li>
        <li class="mb15"><a href="list.html">3万以下</a></li>
        <li class="mb15"><a href="list.html">3-5万</a></li>
        <li class="mb15"><a href="list.html">5-8万</a></li>
        <li class="mb15"><a href="list.html">8-12万</a></li>
        <li class="mb15"><a href="list.html">12-20万</a></li>
        <li class="mb15"><a href="list.html">20万以上</a></li>
        <li class="mb15"><a href="list.html">大众</a></li>
        <li class="mb15"><a href="list.html">奥迪</a></li>
        <li class="mb15"><a href="list.html">宝马</a></li>
        <li class="mb15"><a href="list.html">奔驰</a></li>
        <li class="mb15"><a href="list.html">本田</a></li>
        <li class="mb15"><a href="list.html">丰田</a></li>
        <li class="mb15"><a href="list.html">日产</a></li>
        <li class="mb15"><a href="list.html">SUV</a></li>
        <li class="mb15"><a href="list.html" class="fcf9">全部品牌</a></li>
    </ul>
</div>
<div class="hot_box mt1  pt1">
    <div class="hot_title bl4">热卖车型<a href="list.html" class="more">更多 >></a></div>
    <div class="good_list mt1 bt1">
        <div class="good_mian">
            <a href="detail.html">
                <div  class="good_img fl"><img src="images/car1.jpg"></div>
                <div class="good_cont pl08 ml9">
                    <h4 class="good_name fc3">现代ix25 2015款 1.6 自动 DLX 两驱尊贵型</h4>
                    <p class="good_descript fc8"><span>2020-11</span>|<span>1.2万公里</span></p>
                    <div class="good_price">¥13.28万</div>
                </div>
            </a>
        </div>
        <div class="good_mian">
            <a href="detail.html">
                <div  class="good_img fl"><img src="images/car1.jpg"></div>
                <div class="good_cont pl08 ml9">
                    <h4 class="good_name fc3">现代ix25 2015款 1.6 自动 DLX 两驱尊贵型</h4>
                    <p class="good_descript fc8"><span>2020-11</span>|<span>1.2万公里</span></p>
                    <div class="good_price">¥13.28万</div>
                </div>
            </a>
        </div>
        <div class="good_mian">
            <a href="detail.html">
                <div  class="good_img fl"><img src="images/car1.jpg"></div>
                <div class="good_cont pl08 ml9">
                    <h4 class="good_name fc3">现代ix25 2015款 1.6 自动 DLX 两驱尊贵型</h4>
                    <p class="good_descript fc8"><span>2020-11</span>|<span>1.2万公里</span></p>
                    <div class="good_price">¥13.28万</div>
                </div>
            </a>
        </div>
        <div class="good_mian">
            <a href="detail.html">
                <div  class="good_img fl"><img src="images/car1.jpg"></div>
                <div class="good_cont pl08 ml9">
                    <h4 class="good_name fc3">现代ix25 2015款 1.6 自动 DLX 两驱尊贵型</h4>
                    <p class="good_descript fc8"><span>2020-11</span>|<span>1.2万公里</span></p>
                    <div class="good_price">¥13.28万</div>
                </div>
            </a>
        </div>
    </div>
</div>
<footer>
    <div class="btn_box"><a href="#" class="buy_btn btc">我要买车</a><a href="#" class="sale_btn btc">我要卖车</a></div>
</footer>
<script src="/js/jquery-1.8.3.min.js"></script>
<script src="/js/amazeui.js"></script>
<style>
    .copyrights{text-indent:-9999px;height:0;line-height:0;font-size:0;overflow:hidden;}
</style>
</body>
</html>
